### PR TITLE
update regex to account for periods in package name

### PR DESCRIPTION
**Pull request by brucewpaul**
this pr address https://github.com/nathanhleung/install-peerdeps/issues/17

### CODE REVIEW

**Comment by brucewpaul** [comment]
hmm, the tests are passing locally...

**Comment by nathanhleung** [comment]
Thanks for this, I didn't even consider that packages could have dots in their name, but thinking of it now all of lodash is published to npm as packages in dot notation.

Also, the same thing has been happening for me with the tests -- they passed locally for the last release but don't pass on Travis. I'm still trying to figure out why and I think it may be an issue with the jest file resolver and the CI environment -- if you figure anything out about it please let me know!

**Comment by nathanhleung** [comment]
One more thing: thanks for the additional tests. They are much appreciated.

**Comment by brucewpaul** [comment]
@nathanhleung do you when you will be able to do a release for this?

**Comment by nathanhleung** [comment]
Sorry for holding you up; just released.

Still stumped on this whole issue with Travis failing, though. :/

**Comment by brucewpaul** [comment]
no worries and thanks!

**Pull request merged**
