### PR TITLE
add explicit --no-save when using silent

### PR DESCRIPTION
**Pull request by brucewpaul**
this pr resolves https://github.com/nathanhleung/install-peerdeps/issues/14

### CODE REVIEW

**Comment by nathanhleung** [comment]
Thanks for this pull! Your changes were great -- I added a few comments and moved it a little for clarity.

I've just merged and will publish a new release soon.

**Comment by brucewpaul** [comment]
Thanks!

**Comment by brucewpaul** [comment]
@nathanhleung will you be able to do a release?

**Comment by nathanhleung** [comment]
@brucewpaul I won't be able to get to it until later this week -- for now, though, you can install straight from Github.

**Comment by ljharb** [comment]
Installing from github doesn't allow us to use our internal npm registry for safe redeployments; we're blocked until you can get to it.

**Comment by nathanhleung** [comment]
@ljharb I gave you commit access for short while but then I realized it'd be easier for me to just publish the package because I've also got access to NPM

I didn't know I was holding you up -- will release ASAP!

**Comment by ljharb** [comment]
Thanks!

**Comment by nathanhleung** [comment]
@brucewpaul @ljharb Just released, added a few tests along the way. Thanks again for the contribution.

**Comment by ljharb** [comment]
Thank you!

**Comment by brucewpaul** [comment]
thanks!

**Pull request merged**
