### PR TITLE
[Tests] convert tests to tape, to support older nodes

### LINKED ISSUE #26: tests are failing on Node 0.10
need to get tests working on 0.10

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #26.

### CODE REVIEW

**Comment by ljharb** [comment]
(You may also want to edit the protected branch settings and make travis-ci a required check)

**Comment by ljharb** [comment]
np, I can modify this PR to gitignore yarn.lock as well, if you're OK with that?

**Comment by nathanhleung** [comment]
That would be great!

**Comment by ljharb** [comment]
Updated :-)

**Comment by nathanhleung** [comment]
No test output was showing up on my end, but it was just a quick fix (tape needed to run the tests in `tests`, not `build-test`).

I'm releasing 1.8.0 right now!

**Comment by ljharb** [comment]
That was on purpose; tests need to run on the babel output and not on the original tests.

**Comment by nathanhleung** [comment]
The tests are colocated with the source files in `src/`, so running `build:test` resulted in Babel output of both tests and sources in `test/`:

`"build:test": "babel src --out-dir test"`
`"tests-only": "npm run tape 'build-test/*.test.js'"`

The tests were originally passing in Travis because no tests were run and the script was exiting with 0, not because they were actually run! Changing the `tests-only` script to below allowed the TAP output to show:

`"tests-only": "npm run tape test/*.test.js"`

**Comment by ljharb** [comment]
ahhhh got it. Thanks for fixing that :-)

**Pull request merged**
