### PR TITLE
[Fix] inline `has-yarn`, to restore compat to older nodes

### LINKED ISSUE #27: `has-yarn` uses `const`
Instead of using `has-yarn` - since it uses `const` and an arrow function, could we just inline this simple oneliner? https://unpkg.com/has-yarn@1.0.0/index.js

This is needed to allow enzyme-adapter-react-helper to work on older nodes.

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #27

### CODE REVIEW

**Comment by nathanhleung** [comment]
Thanks for the pull request and thanks for fixing the tests!

**Comment by nathanhleung** [comment]
ALso, could you explain what the `matrix` entry in .travis.yml does, exactly? I see it runs the scripts but I'm not exactly sure why some entries are in `include` and others are in the top-level config.

**Comment by ljharb** [comment]
The top-level config currently only has one env entry, so it runs that for each of the node versions. The "include" is for one-offs - ie, include 1 lint run, and run "TEST" for all the nodes.

You might add additional one-offs, or additional variants that you want to run in "all nodes"

**Comment by ljharb** [comment]
(and thanks! looking forward to this being released)

**Comment by nathanhleung** [comment]
Been having problems publishing on my Windows box lately but will try and release ASAP!

**Pull request merged**
